### ISSUE TITLE
Language changing before pressing the okay button.

### ISSUE THREAD

**Issue by prashanthd** [ahmedaljazzar/LanguageSwitcher#18] opened 2017-02-06 11:23 UTC
Hi,
Suppose there are two languages A,B and default selected one is A. I opened the the ChangeLanguageDialog. I selected the language B but pressed the Cancel. Still when I try to get strings I should get  String in language A, but I am getting in Language B. After reloading the activity It is loading the String of A language.

**Comment by adheesh24** [comment] 2017-02-13 04:54
@ahmedaljazzar - I am facing the same issue. Can you look into it and reply at the earliest? As it has already been over a week since the issue has been posted.

**Comment by iamjazzar** [comment] 2017-02-13 10:46
Hello all,
I just reproduced the bug and it's valid, it'll be solved in the next version. The problem is that I did not handle the cancelation method well.

Thanks for reporting.

**Comment by adheesh24** [comment] 2017-02-14 08:05
Hi,
Thanks a lot @ahmedaljazzar . Can you please notify me in this window once you release the next version?

Thanks,
Adheesh

**Comment by adheesh24** [comment] 2017-02-22 06:15
Hi @ahmedaljazzar,
Could you resolve this at the earliest? As I am using this library for language change and want to continue using it. 
In case if you are tied up with something else and not able to resolve it please let me know so that I can use any other library.

Thanks,
Adheesh

**Comment by iamjazzar** [comment] 2017-02-22 19:42
It should be fixed in #19, will be deployed soon.

**Comment by iamjazzar** [comment] 2017-02-24 11:50
This is now fixed in version 1.0.1 of Rosetta which has just been released.

**Closed as completed by iamjazzar** 2017-02-24 11:50 UTC
Labels: bug

**Comment by adheesh24** [comment] 2017-02-24 14:23
Thanks a lot @ahmedaljazzar
